Repository cocos-pet/cocos-backend, pull requests merged in 2025-05, with the labels that each got.

#193 Feat: 회원 탈퇴 API 구현
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/db/comment/repository/CommentRepository.java
  src/main/java/com/cocos/cocos/db/comment/repository/SubCommentRepository.java
  src/main/java/com/cocos/cocos/db/member/repository/MemberAddressRepository.java
  src/main/java/com/cocos/cocos/db/post/repository/PostImageRepository.java
  src/main/java/com/cocos/cocos/db/post/repository/PostLikeRepository.java
  src/main/java/com/cocos/cocos/db/post/repository/PostRepository.java
  src/main/java/com/cocos/cocos/db/post/repository/PostTagRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewImageRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewSummaryRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewSymptomRepository.java
  src/main/java/com/cocos/cocos/db/search/repository/SearchRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/main/java/com/cocos/cocos/external/KakaoLoginClient.java
  src/main/java/com/cocos/cocos/external/login/dto/KakaoUnlinkRequest.java
  src/main/java/com/cocos/cocos/external/login/dto/KakaoUnlinkResponse.java
Labels: 🍀feat

#192 Feat: 병원 리뷰 삭제 API
  src/main/java/com/cocos/cocos/api/review/controller/ReviewController.java
  src/main/java/com/cocos/cocos/api/review/controller/ReviewControllerSwagger.java
  src/main/java/com/cocos/cocos/api/review/dto/response/ReviewImageDeleteListResponse.java
  src/main/java/com/cocos/cocos/api/review/service/ReviewService.java
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewImageRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewSummaryRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewSymptomRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/main/java/com/cocos/cocos/external/MemberDataS3Client.java
  src/main/java/com/cocos/cocos/validation/disease/DiseaseIdValidator.java
  src/main/java/com/cocos/cocos/validation/review/ReviewIdConstraint.java
  src/main/java/com/cocos/cocos/validation/review/ReviewIdValidator.java
  src/test/java/com/cocos/cocos/review/ReviewServiceTest.java
Labels: 🍀feat

#194 Feat: 사용자 리뷰 리스트 조회 API 구현
  src/main/java/com/cocos/cocos/api/review/controller/ReviewController.java
  src/main/java/com/cocos/cocos/api/review/controller/ReviewControllerSwagger.java
  src/main/java/com/cocos/cocos/api/review/dto/response/MemberHospitalReviewListResponse.java
  src/main/java/com/cocos/cocos/api/review/dto/response/MemberHospitalReviewResponse.java
  src/main/java/com/cocos/cocos/api/review/service/ReviewService.java
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewImageRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewSummaryRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewSymptomRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/main/java/com/cocos/cocos/validation/review/ReviewIdConstraint.java
Labels: 🍀feat

#199 Feat: 리뷰 리스트 조회 API 구현
  src/main/java/com/cocos/cocos/api/hospital/service/HospitalService.java
  src/main/java/com/cocos/cocos/api/location/service/LocationService.java
  src/main/java/com/cocos/cocos/api/review/controller/ReviewController.java
  src/main/java/com/cocos/cocos/api/review/controller/ReviewControllerSwagger.java
  src/main/java/com/cocos/cocos/api/review/dto/request/ReviewListRequest.java
  src/main/java/com/cocos/cocos/api/review/dto/response/HospitalReviewListResponse.java
  src/main/java/com/cocos/cocos/api/review/dto/response/HospitalReviewResponse.java
  src/main/java/com/cocos/cocos/api/review/service/ReviewService.java
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
  src/main/java/com/cocos/cocos/db/district/repository/DistrictRepository.java
  src/main/java/com/cocos/cocos/db/hospital/repository/HospitalRepository.java
  src/main/java/com/cocos/cocos/db/pet/repository/PetRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewSymptomRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/test/java/com/cocos/cocos/location/LocationServiceTest.java
Labels: 🍀feat

#200 Fix: locationType, locationId 없이도 오류 없이 hospital list 조회할 수 있도록 수정
  src/main/java/com/cocos/cocos/api/hospital/service/HospitalService.java
  src/main/java/com/cocos/cocos/db/hospital/repository/HospitalRepository.java
Labels: 🔧Fix

#206 Fix: 기본 주소 강남구로 수정
  src/main/java/com/cocos/cocos/db/member/entity/MemberAddress.java
Labels: 🔧Fix

#202 Fix: 게시글 content 타입 text로 변경
  src/main/java/com/cocos/cocos/db/post/entity/Post.java
Labels: 🔧Fix

#209 Hotfix: 사용자 즐겨찾는 병원 조회 API 응답에 병원 이미지 추가
  src/main/java/com/cocos/cocos/api/member/dto/response/MemberHospitalResponse.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/external/AppDataS3Client.java
Labels: 😈 hotfix

#203 Fix: 토큰 에러 세분화
  src/main/java/com/cocos/cocos/auth/JwtProvider.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
Labels: 🔧Fix

#204 Fix: 카카오 로그인 시 토큰 및 사용자 정보 조회 시 Null 값 확인 후 예외처리
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/main/java/com/cocos/cocos/external/KakaoLoginClient.java
Labels: 🔧Fix

#207 Fix: 리뷰 작성 시 reviewCount 증가 로직 추가
  src/main/java/com/cocos/cocos/api/review/service/ReviewService.java
Labels: 🔧Fix

#210 Fix: 리뷰 리스트 반환 응답에 방문 목적 필드 추가
  src/main/java/com/cocos/cocos/api/review/dto/response/HospitalReviewResponse.java
  src/main/java/com/cocos/cocos/api/review/dto/response/MemberHospitalReviewResponse.java
  src/main/java/com/cocos/cocos/api/review/service/ReviewService.java
Labels: 🔧Fix

#220 Fix: health-check api white list에 추가
  src/main/java/com/cocos/cocos/api/pet/controller/PetControllerSwagger.java
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
  src/main/java/com/cocos/cocos/test/controller/TestController.java
Labels: 🔧Fix

#219 Fix: 병원, 리뷰 API 비로그인 로직 추가
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/review/controller/ReviewController.java
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
Labels: 🔧Fix

#222 Fix: 종류(breed) 검색 시 찾는 종이 없음 선택지 추가
  src/main/java/com/cocos/cocos/api/breed/controller/BreedControllerSwagger.java
  src/main/java/com/cocos/cocos/api/breed/service/BreedService.java
  src/main/java/com/cocos/cocos/db/breed/entity/Breed.java
  src/main/java/com/cocos/cocos/db/breed/repository/BreedRepository.java
Labels: 🔧Fix

#226 Fix: 마이페이지 조회 시 pet 검증 로직 제거
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/review/controller/ReviewController.java
Labels: 🔧Fix

#228 Fix: 사용자 리뷰 리스트 조회 시에도 disease id가 null일 수 있도록 수정
  src/main/java/com/cocos/cocos/api/review/service/ReviewService.java
Labels: 🔧Fix
