Repository cocos-pet/cocos-backend, pull requests merged in 2025-01, with the labels that each got.

#11 Feat: Swagger 세팅
  build.gradle
  src/main/java/com/cocos/cocos/config/SwaggerConfig.java
  src/main/java/com/cocos/cocos/test/controller/TestController.java
  src/main/java/com/cocos/cocos/test/controller/TestControllerSwagger.java
  src/main/resources/application.properties
Labels: 🍀feat

#13 Feat: Entity세팅
  src/main/java/com/cocos/cocos/config/JpaAuditingConfig.java
  src/main/java/com/cocos/cocos/db/BaseTime.java
  src/main/java/com/cocos/cocos/db/animal/entity/Animal.java
  src/main/java/com/cocos/cocos/db/animal/repository/AnimalRepository.java
  src/main/java/com/cocos/cocos/db/body/entity/Body.java
  src/main/java/com/cocos/cocos/db/body/repository/BodyRepository.java
  src/main/java/com/cocos/cocos/db/breed/entity/Breed.java
  src/main/java/com/cocos/cocos/db/breed/repository/BreedRepository.java
  src/main/java/com/cocos/cocos/db/category/entity/Category.java
  src/main/java/com/cocos/cocos/db/category/repository/CategoryRepository.java
  src/main/java/com/cocos/cocos/db/comment/entity/Comment.java
  src/main/java/com/cocos/cocos/db/comment/repository/CommentRepository.java
  src/main/java/com/cocos/cocos/db/disease/entity/Disease.java
  src/main/java/com/cocos/cocos/db/disease/repository/DiseaseRepository.java
  src/main/java/com/cocos/cocos/db/diseasesymptom/entity/DiseaseSymptom.java
  src/main/java/com/cocos/cocos/db/diseasesymptom/repository/DiseaseSymptomRepository.java
  src/main/java/com/cocos/cocos/db/heart/entity/Heart.java
  src/main/java/com/cocos/cocos/db/heart/repository/HeartRepository.java
  src/main/java/com/cocos/cocos/db/hospital/entity/Hospital.java
  src/main/java/com/cocos/cocos/db/hospital/repository/HospitalRepository.java
  src/main/java/com/cocos/cocos/db/image/entity/Image.java
  src/main/java/com/cocos/cocos/db/image/repository/ImageRepository.java
  src/main/java/com/cocos/cocos/db/member/entity/Member.java
  src/main/java/com/cocos/cocos/db/member/repository/MemberRepository.java
  src/main/java/com/cocos/cocos/db/memberhospital/entity/MemberHospital.java
  src/main/java/com/cocos/cocos/db/memberhospital/repository/MemberHospitalRepository.java
  src/main/java/com/cocos/cocos/db/pet/entity/Pet.java
  src/main/java/com/cocos/cocos/db/pet/repository/PetRepository.java
  src/main/java/com/cocos/cocos/db/petdisease/entity/PetDisease.java
  src/main/java/com/cocos/cocos/db/petdisease/repository/PetDiseaseRepository.java
  src/main/java/com/cocos/cocos/db/petsymptom/entity/PetSymptom.java
  src/main/java/com/cocos/cocos/db/petsymptom/repository/PetSymptomRepository.java
  src/main/java/com/cocos/cocos/db/post/entity/Post.java
  src/main/java/com/cocos/cocos/db/post/repository/PostRepository.java
  src/main/java/com/cocos/cocos/db/search/entity/Search.java
  src/main/java/com/cocos/cocos/db/search/repository/SearchRepository.java
  src/main/java/com/cocos/cocos/db/subcomment/entity/SubComment.java
  src/main/java/com/cocos/cocos/db/subcomment/repository/SubCommentRepository.java
  src/main/java/com/cocos/cocos/db/symptom/entity/Symptom.java
  src/main/java/com/cocos/cocos/db/symptom/repository/SymptomRepository.java
  src/main/java/com/cocos/cocos/db/tag/entity/Tag.java
  src/main/java/com/cocos/cocos/db/tag/repository/TagRepository.java
  src/main/java/com/cocos/cocos/db/token/entity/Token.java
  src/main/java/com/cocos/cocos/db/token/repository/TokenRepository.java
  src/main/java/com/cocos/cocos/enums/member/Platform.java
  src/main/java/com/cocos/cocos/enums/pet/Gender.java
  src/main/java/com/cocos/cocos/enums/tag/TagType.java
Labels: 🍀feat

#14 Feat: API 공통 응답 형식 및 global exception 세팅
  src/main/java/com/cocos/cocos/common/exception/CocosException.java
  src/main/java/com/cocos/cocos/common/handler/GlobalExceptionHandler.java
  src/main/java/com/cocos/cocos/common/response/BaseResponse.java
  src/main/java/com/cocos/cocos/common/response/FailResponse.java
  src/main/java/com/cocos/cocos/common/response/SuccessResponse.java
  src/main/java/com/cocos/cocos/common/response/message/ApiMessage.java
  src/main/java/com/cocos/cocos/common/response/message/FailMessage.java
  src/main/java/com/cocos/cocos/common/response/message/SuccessMessage.java
Labels: 🍀feat

#19 Feat: 게시글 공감 추가 API 및 게시글 공감 삭제 API 구현
  src/main/java/com/cocos/cocos/api/post/controller/PostLikeController.java
  src/main/java/com/cocos/cocos/api/post/controller/PostLikeControllerSwagger.java
  src/main/java/com/cocos/cocos/api/post/service/PostLikeService.java
  src/main/java/com/cocos/cocos/common/response/SuccessResponse.java
  src/main/java/com/cocos/cocos/db/post/entity/PostLike.java
  src/main/java/com/cocos/cocos/db/post/repository/PostLikeRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/main/java/com/cocos/cocos/enums/message/SuccessMessage.java
  src/test/java/com/cocos/cocos/post/PostLikeTest.java
Labels: 🍀feat

#24 Feat: 품종 조회, 신체 부위 조회, 질병 조회, 증상 조회 API 구현
  src/main/java/com/cocos/cocos/api/body/controller/BodyController.java
  src/main/java/com/cocos/cocos/api/body/controller/BodyControllerSwagger.java
  src/main/java/com/cocos/cocos/api/body/dto/response/BodiesResponse.java
  src/main/java/com/cocos/cocos/api/body/dto/response/BodyResponse.java
  src/main/java/com/cocos/cocos/api/body/service/BodyService.java
  src/main/java/com/cocos/cocos/api/breed/controller/BreedController.java
  src/main/java/com/cocos/cocos/api/breed/controller/BreedControllerSwagger.java
  src/main/java/com/cocos/cocos/api/breed/dto/response/BreedResponse.java
  src/main/java/com/cocos/cocos/api/breed/dto/response/BreedsResponse.java
  src/main/java/com/cocos/cocos/api/breed/service/BreedService.java
  src/main/java/com/cocos/cocos/api/disease/controller/DiseaseController.java
  src/main/java/com/cocos/cocos/api/disease/controller/DiseaseControllerSwagger.java
  src/main/java/com/cocos/cocos/api/disease/dto/response/DiseaseResponse.java
  src/main/java/com/cocos/cocos/api/disease/dto/response/DiseasesOfBodiesResponse.java
  src/main/java/com/cocos/cocos/api/disease/dto/response/DiseasesOfBodyResponse.java
  src/main/java/com/cocos/cocos/api/disease/service/DiseaseService.java
  src/main/java/com/cocos/cocos/api/symptom/controller/SymptomController.java
  src/main/java/com/cocos/cocos/api/symptom/controller/SymptomControllerSwagger.java
  src/main/java/com/cocos/cocos/api/symptom/dto/response/SymptomResponse.java
  src/main/java/com/cocos/cocos/api/symptom/dto/response/SymptomsOfBodiesResponse.java
  src/main/java/com/cocos/cocos/api/symptom/dto/response/SymptomsOfBodyResponse.java
  src/main/java/com/cocos/cocos/api/symptom/service/SymptomService.java
  src/main/java/com/cocos/cocos/db/body/entity/Body.java
  src/main/java/com/cocos/cocos/db/breed/entity/Breed.java
  src/main/java/com/cocos/cocos/db/breed/repository/BreedRepository.java
  src/main/java/com/cocos/cocos/db/disease/entity/Disease.java
  src/main/java/com/cocos/cocos/db/disease/repository/DiseaseRepository.java
  src/main/java/com/cocos/cocos/db/symptom/entity/Symptom.java
  src/main/java/com/cocos/cocos/db/symptom/repository/SymptomRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/test/java/com/cocos/cocos/animal/AnimalServiceTest.java
  src/test/java/com/cocos/cocos/body/BodyServiceTest.java
  src/test/java/com/cocos/cocos/breed/BreedRepositoryTest.java
  src/test/java/com/cocos/cocos/breed/BreedServiceTest.java
  src/test/java/com/cocos/cocos/diseases/DiseaseServiceTest.java
  src/test/java/com/cocos/cocos/post/PostLikeServiceTest.java
  src/test/java/com/cocos/cocos/symptom/SymptomServiceTest.java
Labels: 🍀feat

#27 Feat: add getPostComments API
  src/main/java/com/cocos/cocos/api/comment/controller/CommentController.java
  src/main/java/com/cocos/cocos/api/comment/controller/CommentControllerSwagger.java
  src/main/java/com/cocos/cocos/api/comment/dto/response/CommentsAndSubCommentsResponse.java
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
  src/main/java/com/cocos/cocos/db/comment/entity/Comment.java
  src/main/java/com/cocos/cocos/db/comment/entity/SubComment.java
  src/main/java/com/cocos/cocos/db/comment/repository/CommentRepository.java
  src/main/java/com/cocos/cocos/db/comment/repository/SubCommentRepository.java
  src/main/java/com/cocos/cocos/db/member/entity/Member.java
  src/main/java/com/cocos/cocos/db/pet/entity/Pet.java
  src/main/java/com/cocos/cocos/db/pet/repository/PetRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/main/java/com/cocos/cocos/external/MemberDataS3Client.java
Labels: 🍀feat

#26 Feat: 최근 검색어 조회, 게시글 상세 조회, 게시글 삭제, 게시글 카테고리 조회 API 구현
  src/main/java/com/cocos/cocos/api/post/controller/PostController.java
  src/main/java/com/cocos/cocos/api/post/controller/PostControllerSwagger.java
  src/main/java/com/cocos/cocos/api/post/dto/response/PostCategoriesResponse.java
  src/main/java/com/cocos/cocos/api/post/dto/response/PostCategoryResponse.java
  src/main/java/com/cocos/cocos/api/post/dto/response/PostDetailResponse.java
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
  src/main/java/com/cocos/cocos/api/search/controller/SearchController.java
  src/main/java/com/cocos/cocos/api/search/controller/SearchControllerSwagger.java
  src/main/java/com/cocos/cocos/api/search/dto/response/KeywordResponse.java
  src/main/java/com/cocos/cocos/api/search/dto/response/SearchResponse.java
  src/main/java/com/cocos/cocos/api/search/service/SearchService.java
  src/main/java/com/cocos/cocos/db/comment/repository/CommentRepository.java
  src/main/java/com/cocos/cocos/db/comment/repository/SubCommentRepository.java
  src/main/java/com/cocos/cocos/db/pet/repository/PetRepository.java
  src/main/java/com/cocos/cocos/db/post/entity/Post.java
  src/main/java/com/cocos/cocos/db/post/entity/PostCategory.java
  src/main/java/com/cocos/cocos/db/post/entity/PostImage.java
  src/main/java/com/cocos/cocos/db/post/entity/PostTag.java
  src/main/java/com/cocos/cocos/db/post/repository/PostImageRepository.java
  src/main/java/com/cocos/cocos/db/post/repository/PostLikeRepository.java
  src/main/java/com/cocos/cocos/db/post/repository/PostTagRepository.java
  src/main/java/com/cocos/cocos/db/search/entity/Search.java
  src/main/java/com/cocos/cocos/db/search/repository/SearchRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/test/java/com/cocos/cocos/post/PostServiceTest.java
  src/test/java/com/cocos/cocos/search/SearchServiceTest.java
Labels: 🍀feat

#30 Fix: 댓글 응답 파일 분리, 스웨거 스키마 추가
  src/main/java/com/cocos/cocos/api/comment/dto/response/CommentAndSubCommentsResponse.java
  src/main/java/com/cocos/cocos/api/comment/dto/response/CommentsAndSubCommentsResponse.java
  src/main/java/com/cocos/cocos/api/comment/dto/response/SubCommentResponse.java
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
Labels: 🔧Fix

#32 Feat: 게시글 댓글&대댓글 추가와 삭제 API 구현
  src/main/java/com/cocos/cocos/api/comment/controller/CommentController.java
  src/main/java/com/cocos/cocos/api/comment/controller/CommentControllerSwagger.java
  src/main/java/com/cocos/cocos/api/comment/dto/request/CommentContentRequest.java
  src/main/java/com/cocos/cocos/api/comment/dto/request/SubCommentContentRequest.java
  src/main/java/com/cocos/cocos/api/comment/dto/response/CommentAndSubCommentsResponse.java
  src/main/java/com/cocos/cocos/api/comment/dto/response/SubCommentResponse.java
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
  src/main/java/com/cocos/cocos/api/post/controller/PostControllerSwagger.java
  src/main/java/com/cocos/cocos/db/comment/entity/SubComment.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/test/java/com/cocos/cocos/comment/CommentServiceTest.java
Labels: 🍀feat

#33 Feat: 인기글 조회, 게시글 작성 API 구현
  src/main/java/com/cocos/cocos/api/post/controller/PostController.java
  src/main/java/com/cocos/cocos/api/post/controller/PostControllerSwagger.java
  src/main/java/com/cocos/cocos/api/post/dto/request/PostRequest.java
  src/main/java/com/cocos/cocos/api/post/dto/response/PopularPostResponse.java
  src/main/java/com/cocos/cocos/api/post/dto/response/PopularPostsResponse.java
  src/main/java/com/cocos/cocos/api/post/dto/response/PostImagesResponse.java
  src/main/java/com/cocos/cocos/api/post/service/PostLikeService.java
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
  src/main/java/com/cocos/cocos/config/SwaggerConfig.java
  src/main/java/com/cocos/cocos/db/pet/entity/PetDisease.java
  src/main/java/com/cocos/cocos/db/pet/entity/PetSymptom.java
  src/main/java/com/cocos/cocos/db/pet/repository/PetDiseaseRepository.java
  src/main/java/com/cocos/cocos/db/pet/repository/PetRepository.java
  src/main/java/com/cocos/cocos/db/pet/repository/PetSymptomRepository.java
  src/main/java/com/cocos/cocos/db/post/entity/Post.java
  src/main/java/com/cocos/cocos/db/post/repository/PostRepository.java
  src/main/java/com/cocos/cocos/db/post/repository/PostTagRepository.java
  src/main/java/com/cocos/cocos/external/MemberDataS3Client.java
  src/test/java/com/cocos/cocos/post/PostLikeServiceTest.java
  src/test/java/com/cocos/cocos/post/PostRepositoryTest.java
  src/test/java/com/cocos/cocos/post/PostServiceTest.java
Labels: 🍀feat

#40 Feat: 게시글 리스트 조회 API 구현
  src/main/java/com/cocos/cocos/api/body/controller/BodyController.java
  src/main/java/com/cocos/cocos/api/body/controller/BodyControllerSwagger.java
  src/main/java/com/cocos/cocos/api/body/service/BodyService.java
  src/main/java/com/cocos/cocos/api/post/controller/PostController.java
  src/main/java/com/cocos/cocos/api/post/dto/request/PostListRequest.java
  src/main/java/com/cocos/cocos/api/post/dto/response/PostListResponse.java
  src/main/java/com/cocos/cocos/api/post/dto/response/PostResponse.java
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
  src/main/java/com/cocos/cocos/api/search/controller/SearchController.java
  src/main/java/com/cocos/cocos/api/search/controller/SearchControllerSwagger.java
  src/main/java/com/cocos/cocos/api/search/service/SearchService.java
  src/main/java/com/cocos/cocos/config/WebConfig.java
  src/main/java/com/cocos/cocos/db/BaseTime.java
  src/main/java/com/cocos/cocos/db/post/repository/PostRepository.java
  src/main/java/com/cocos/cocos/db/search/repository/SearchRepository.java
  src/main/java/com/cocos/cocos/enums/pet/PetProblem.java
  src/main/java/com/cocos/cocos/enums/post/SortCriteria.java
  src/main/java/com/cocos/cocos/util/PetProblemEnumConverter.java
  src/main/java/com/cocos/cocos/util/PostSpecification.java
  src/main/java/com/cocos/cocos/util/SortCriteriaEnumConverter.java
  src/test/java/com/cocos/cocos/body/BodyServiceTest.java
  src/test/java/com/cocos/cocos/search/SearchServiceTest.java
Labels: 🍀feat

#43 Feat: 사용자 게시글 조회 API 및 사용자 정보 조회 API 구현
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberControllerSwagger.java
  src/main/java/com/cocos/cocos/api/member/dto/response/MemberProfileResponse.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/api/post/controller/PostController.java
  src/main/java/com/cocos/cocos/api/post/controller/PostControllerSwagger.java
  src/main/java/com/cocos/cocos/api/post/dto/response/MemberPostDetailResponse.java
  src/main/java/com/cocos/cocos/api/post/dto/response/MemberPostsResponse.java
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
  src/main/java/com/cocos/cocos/db/post/repository/PostRepository.java
Labels: 🍀feat

#46 Feat: 사용자 정보 수정 API 구현
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberControllerSwagger.java
  src/main/java/com/cocos/cocos/api/member/dto/response/NicknameExistenceResponse.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/db/member/entity/Member.java
  src/main/java/com/cocos/cocos/db/member/repository/MemberRepository.java
Labels: 🍀feat

#48 Fix: 닉네임으로 회원 페이지 정보 조회할 수 있도록 변경
  src/main/java/com/cocos/cocos/api/comment/controller/CommentController.java
  src/main/java/com/cocos/cocos/api/comment/controller/CommentControllerSwagger.java
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberControllerSwagger.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
Labels: 🔧Fix

#49 Feat: 로그인, 로그아웃 및 토큰 재발급 API 구현
  build.gradle
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberControllerSwagger.java
  src/main/java/com/cocos/cocos/api/member/dto/request/LoginRequest.java
  src/main/java/com/cocos/cocos/api/member/dto/response/LoginResponse.java
  src/main/java/com/cocos/cocos/api/member/dto/response/MemberProfileResponse.java
  src/main/java/com/cocos/cocos/api/member/dto/response/ReissueTokenResponse.java
  src/main/java/com/cocos/cocos/api/member/dto/response/TokenResponse.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/api/post/controller/PostLikeController.java
  src/main/java/com/cocos/cocos/auth/CustomAccessDeniedHandler.java
  src/main/java/com/cocos/cocos/auth/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/cocos/cocos/auth/JwtAuthenticationFilter.java
  src/main/java/com/cocos/cocos/auth/JwtProvider.java
  src/main/java/com/cocos/cocos/auth/MemberAuthentication.java
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
  src/main/java/com/cocos/cocos/config/WebConfig.java
  src/main/java/com/cocos/cocos/db/member/entity/MemberToken.java
  src/main/java/com/cocos/cocos/db/member/repository/MemberRepository.java
  src/main/java/com/cocos/cocos/db/member/repository/MemberTokenRepository.java
  src/main/java/com/cocos/cocos/enums/auth/JwtValidationType.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/main/java/com/cocos/cocos/external/KakaoLoginClient.java
  src/main/java/com/cocos/cocos/external/login/dto/KakaoAccessTokenResponse.java
  src/main/java/com/cocos/cocos/external/login/dto/KakaoAccount.java
  src/main/java/com/cocos/cocos/external/login/dto/KakaoInfoResponse.java
  src/main/java/com/cocos/cocos/test/controller/TestController.java
  src/main/java/com/cocos/cocos/util/PrincipalHandler.java
Labels: 🍀feat

#53 Fix: swagger url 수정
  src/main/java/com/cocos/cocos/config/SwaggerConfig.java
Labels: 🔧Fix

#54 Fix: CORS 수정
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
  src/main/java/com/cocos/cocos/config/SwaggerConfig.java
Labels: 🔧Fix

#55 Fix: swagger 서버 환경 분리
  src/main/java/com/cocos/cocos/config/SwaggerConfig.java
Labels: 🔧Fix

#58 Fix: cors 설정
  src/main/java/com/cocos/cocos/config/WebConfig.java
Labels: 🔧Fix

#60 Fix: cors 설정
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
Labels: 🔧Fix

#61 Fix: cors 설정
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
Labels: 🔧Fix

#62 Fix: cors 설정
  src/main/java/com/cocos/cocos/config/CorsConfig.java
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
Labels: 🔧Fix

#72 Fix: member 데이터에서 가져오도록 수정
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
Labels: 🔧Fix

#63 Feat: 닉네임 중복 조회 API 구현
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberControllerSwagger.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
Labels: 🍀feat

#65 Fix: 댓글 삭제 파라미터 수정
  src/main/java/com/cocos/cocos/api/comment/controller/CommentController.java
Labels: 🔧Fix

#67 Fix: 대댓글 추가 시 언급된 사용자가 유효한지 확인하는 로직 추가
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
Labels: 🔧Fix

#70 Fix: 애완동물 없을 때의 오류 메시지 수정
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
Labels: 🔧Fix

#74 Fix: 게시글 조회 시 memberData bucket에서 가져오도록 수정
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
Labels: 🔧Fix

#76 Fix: 품종 조회 시 breedName 선택적 필드로 받을 수 있도록 수정
  src/main/java/com/cocos/cocos/api/breed/controller/BreedController.java
  src/main/java/com/cocos/cocos/api/breed/controller/BreedControllerSwagger.java
  src/main/java/com/cocos/cocos/api/breed/service/BreedService.java
  src/main/java/com/cocos/cocos/db/breed/repository/BreedRepository.java
Labels: 🔧Fix

#78 Fix: save할 때 동시성 제어
  .github/ISSUE_TEMPLATE/issue_template.md
  src/main/java/com/cocos/cocos/api/search/controller/SearchController.java
  src/main/java/com/cocos/cocos/api/search/service/SearchService.java
Labels: 🔧Fix

#80 Fix: memberId 토큰 추출 방식으로 변경
  src/main/java/com/cocos/cocos/api/body/controller/BodyControllerSwagger.java
  src/main/java/com/cocos/cocos/api/comment/controller/CommentController.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/pet/controller/PetController.java
  src/main/java/com/cocos/cocos/api/post/controller/PostController.java
  src/main/java/com/cocos/cocos/api/post/controller/PostLikeController.java
  src/main/java/com/cocos/cocos/api/search/controller/SearchController.java
Labels: 🔧Fix

#82 Fix: s3에서 이미지 가져올 때 조합하지 않고 가져오도록 수정
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
Labels: 🔧Fix

#87 Fix: 좋아요 적용 여부, cors, 기본 image url 저장 및 s3 예외 처리
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/api/post/controller/PostController.java
  src/main/java/com/cocos/cocos/api/post/dto/response/PostDetailResponse.java
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
  src/main/java/com/cocos/cocos/config/CorsConfig.java
  src/main/java/com/cocos/cocos/config/WebConfig.java
  src/main/java/com/cocos/cocos/external/MemberDataS3Client.java
  src/test/java/com/cocos/cocos/post/PostServiceTest.java
Labels: 🔧Fix

#95 Fix: Pet 정보 수정 시 오류 수정
  src/main/java/com/cocos/cocos/api/pet/service/PetService.java
  src/main/java/com/cocos/cocos/db/disease/repository/DiseaseRepository.java
  src/main/java/com/cocos/cocos/db/symptom/repository/SymptomRepository.java
Labels: 🔧Fix

#100 Fix: 댓글, 대댓글 달 때 반려동물 있는지 확인하는 로직 추가
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
Labels: 🔧Fix

#102 Fix: Pet 예외처리와 기본 이미지 경로 설정
  src/main/java/com/cocos/cocos/api/pet/service/PetService.java
Labels: 🔧Fix

#104 Refactor: Swagger와 노션 API 명세서 싱크 동기화
  src/main/java/com/cocos/cocos/api/comment/controller/CommentController.java
  src/main/java/com/cocos/cocos/api/comment/controller/CommentControllerSwagger.java
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
  src/main/java/com/cocos/cocos/api/member/dto/request/LoginRequest.java
  src/main/java/com/cocos/cocos/api/pet/dto/reponse/PetResponse.java
  src/main/java/com/cocos/cocos/api/pet/dto/request/PetCreateRequest.java
  src/main/java/com/cocos/cocos/api/pet/dto/request/PetUpdateRequest.java
  src/main/java/com/cocos/cocos/api/post/controller/PostController.java
  src/main/java/com/cocos/cocos/api/post/controller/PostControllerSwagger.java
  src/main/java/com/cocos/cocos/api/post/dto/request/PostListRequest.java
  src/main/java/com/cocos/cocos/api/search/dto/response/SearchResponse.java
Labels: 💌 refactor

#106 Fix: 사용자 댓글 조회 시 게시글을 찾을 수 없는 오류 해결
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
  src/main/java/com/cocos/cocos/db/comment/repository/CommentRepository.java
  src/main/java/com/cocos/cocos/db/comment/repository/SubCommentRepository.java
Labels: 🔧Fix

#108 Fix: 게시글 대댓글 추가 API에서 nickname을 넘겨받도록 수정
  src/main/java/com/cocos/cocos/api/comment/controller/CommentController.java
  src/main/java/com/cocos/cocos/api/comment/dto/request/SubCommentContentRequest.java
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
Labels: 🔧Fix

#110 Fix: 사용자 이미지 S3 URL 변경 및 닉네임 nullable 수정
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/db/member/entity/Member.java
Labels: 🔧Fix

#117 Fix: 질병, 증상, 동물 리스트 null값이 아닌 빈 배열로 판단
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
Labels: 🔧Fix

#119 Fix: 질병, 증상, 동물 리스트 null값도 허용
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
Labels: 🔧Fix

#121 Fix: 게시글 상세 조회 api response에 isWriter 추가
  src/main/java/com/cocos/cocos/api/post/dto/response/PostDetailResponse.java
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
Labels: 🔧Fix

#123 Fix: 사용자 맞춤 인기글이 5개 미만일 경우 전체 중 인기글 5개 반환하도록 수정(데모데이용)
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
Labels: 🔧Fix

#128 Fix: 게시글 작성자와 현재 사용자가 작성한 댓글, 대댓글, 게시글을 구별하는 필드 추가
  src/main/java/com/cocos/cocos/api/comment/dto/response/CommentAndSubCommentsResponse.java
  src/main/java/com/cocos/cocos/api/comment/dto/response/SubCommentResponse.java
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
Labels: 🔧Fix

#132 Fix: 반려동물이 없는 유저는 글을 작성할 수 없도록 수정
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
Labels: 🔧Fix

#133 Hotfix: 신체 아이디를 받으면 그것과 관련된 증상을 가진 게시글 리스트를 보낼 수 있도록 수정
  src/main/java/com/cocos/cocos/api/post/controller/PostController.java
  src/main/java/com/cocos/cocos/api/post/dto/request/PostListRequest.java
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
Labels: 😈 hotfix

#134 Hotfix: 신체 아이디에 대한 증상 아이디를 넘기도록 수정
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
Labels: 😈 hotfix
