Repository cocos-pet/cocos-backend, pull requests merged in 2025-04, with the labels that each got.

#147 Feat: 지역 조회 API 구현
  src/main/java/com/cocos/cocos/api/location/controller/LocationController.java
  src/main/java/com/cocos/cocos/api/location/controller/LocationControllerSwagger.java
  src/main/java/com/cocos/cocos/api/location/dto/response/CityResponse.java
  src/main/java/com/cocos/cocos/api/location/dto/response/DistrictResponse.java
  src/main/java/com/cocos/cocos/api/location/dto/response/LocationResponse.java
  src/main/java/com/cocos/cocos/api/location/service/LocationService.java
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
  src/main/java/com/cocos/cocos/db/city/entity/City.java
  src/main/java/com/cocos/cocos/db/city/repository/CityRepository.java
  src/main/java/com/cocos/cocos/db/district/entity/District.java
  src/main/java/com/cocos/cocos/db/district/repository/DistrictRepository.java
  src/test/java/com/cocos/cocos/location/LocationServiceTest.java
Labels: 🍀feat

#149 Feat: 병원 최근 검색어 조회, 추가 API 구현
  build.gradle
  src/main/java/com/cocos/cocos/api/search/controller/SearchController.java
  src/main/java/com/cocos/cocos/api/search/controller/SearchControllerSwagger.java
  src/main/java/com/cocos/cocos/api/search/service/SearchService.java
  src/main/java/com/cocos/cocos/db/BaseTime.java
  src/main/java/com/cocos/cocos/db/search/entity/Search.java
  src/main/java/com/cocos/cocos/db/search/repository/SearchRepository.java
  src/main/java/com/cocos/cocos/enums/search/SearchType.java
  src/test/java/com/cocos/cocos/search/SearchConcurrencyTest.java
  src/test/java/com/cocos/cocos/search/SearchServiceTest.java
Labels: 🍀feat

#156 Feat: 병원 리스트 조회 API 구현
  build.gradle
  src/main/java/com/cocos/cocos/api/hospital/controller/HospitalController.java
  src/main/java/com/cocos/cocos/api/hospital/controller/HospitalControllerSwagger.java
  src/main/java/com/cocos/cocos/api/hospital/dto/request/HospitalListRequest.java
  src/main/java/com/cocos/cocos/api/hospital/dto/response/HospitalListResponse.java
  src/main/java/com/cocos/cocos/api/hospital/dto/response/HospitalResponse.java
  src/main/java/com/cocos/cocos/api/hospital/service/HospitalService.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/api/post/dto/request/PostListRequest.java
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
  src/main/java/com/cocos/cocos/config/WebConfig.java
  src/main/java/com/cocos/cocos/db/hospital/entity/Hospital.java
  src/main/java/com/cocos/cocos/db/hospital/repository/HospitalRepository.java
  src/main/java/com/cocos/cocos/db/town/entity/Town.java
  src/main/java/com/cocos/cocos/db/town/repository/TownRepository.java
  src/main/java/com/cocos/cocos/enums/hospital/HospitalSortCriteria.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/main/java/com/cocos/cocos/enums/post/PostSortCriteria.java
  src/main/java/com/cocos/cocos/util/PostSortCriteriaEnumConverter.java
  src/main/java/com/cocos/cocos/util/PrincipalHandler.java
  src/main/java/com/cocos/cocos/util/SortConstants.java
  src/main/java/com/cocos/cocos/util/SortCriteriaEnumConverter.java
Labels: 🍀feat

#158 Feat: 사용자 위치(동정보) 조회 API 구현
  src/main/java/com/cocos/cocos/api/comment/service/CommentService.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberControllerSwagger.java
  src/main/java/com/cocos/cocos/api/member/dto/response/MemberLocationResponse.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/api/pet/service/PetService.java
  src/main/java/com/cocos/cocos/api/post/service/PostService.java
  src/main/java/com/cocos/cocos/db/disease/repository/DiseaseRepository.java
  src/main/java/com/cocos/cocos/db/member/entity/Member.java
  src/main/java/com/cocos/cocos/db/member/repository/MemberRepository.java
  src/main/java/com/cocos/cocos/db/symptom/repository/SymptomRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
Labels: 🍀feat

#159 Fix: 사용자 회원정보 업데이트 API 수정
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberControllerSwagger.java
  src/main/java/com/cocos/cocos/api/member/dto/request/ProfileUpdateRequest.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/db/city/repository/CityRepository.java
  src/main/java/com/cocos/cocos/db/district/repository/DistrictRepository.java
  src/main/java/com/cocos/cocos/db/member/entity/Member.java
  src/main/java/com/cocos/cocos/db/member/entity/MemberAddress.java
  src/main/java/com/cocos/cocos/db/member/repository/MemberAddressRepository.java
  src/main/java/com/cocos/cocos/db/town/repository/TownRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
Labels: 🔧Fix

#164 Fix: MemberAddress 필드 수정에 따른 API 수정
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/member/dto/request/ProfileUpdateRequest.java
  src/main/java/com/cocos/cocos/api/member/dto/response/MemberLocationResponse.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/db/member/entity/MemberAddress.java
  src/main/java/com/cocos/cocos/enums/location/LocationType.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/main/java/com/cocos/cocos/util/LocationTypeConvertor.java
Labels: 🔧Fix

#166 Hotfix: 회원가입 시에만 기본 주소 추가하도록 수정
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/db/member/repository/MemberAddressRepository.java
Labels: 😈 hotfix

#168 Feat: 병원 상세 조회 API 구현
  src/main/java/com/cocos/cocos/api/hospital/controller/HospitalController.java
  src/main/java/com/cocos/cocos/api/hospital/controller/HospitalControllerSwagger.java
  src/main/java/com/cocos/cocos/api/hospital/dto/response/HospitalDetailResponse.java
  src/main/java/com/cocos/cocos/api/hospital/service/HospitalService.java
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
  src/main/java/com/cocos/cocos/db/hospital/entity/Hospital.java
  src/main/java/com/cocos/cocos/db/hospital/entity/HospitalTag.java
  src/main/java/com/cocos/cocos/db/hospital/entity/HospitalTagMapping.java
  src/main/java/com/cocos/cocos/db/hospital/repository/HospitalTagMappingRepository.java
  src/main/java/com/cocos/cocos/db/hospital/repository/HospitalTagRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
  src/test/java/com/cocos/cocos/hospital/HospitalServiceTest.java
Labels: 🍀feat

#170 Feat: 병원 리스트 조회 조건 locationId + locationType 기반으로 변경
  src/main/java/com/cocos/cocos/api/hospital/controller/HospitalController.java
  src/main/java/com/cocos/cocos/api/hospital/dto/request/HospitalListRequest.java
  src/main/java/com/cocos/cocos/api/hospital/service/HospitalService.java
  src/main/java/com/cocos/cocos/api/member/dto/response/MemberLocationResponse.java
  src/main/java/com/cocos/cocos/db/hospital/entity/Hospital.java
  src/main/java/com/cocos/cocos/db/hospital/repository/HospitalRepository.java
  src/main/java/com/cocos/cocos/db/town/entity/Town.java
  src/main/java/com/cocos/cocos/db/town/repository/TownRepository.java
Labels: 🍀feat

#175 Feat: 즐겨찾는 병원 API 개발
  src/main/java/com/cocos/cocos/api/hospital/service/HospitalService.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberControllerSwagger.java
  src/main/java/com/cocos/cocos/api/member/dto/response/MemberHospitalResponse.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/config/SecurityConfig.java
  src/main/java/com/cocos/cocos/db/hospital/entity/Hospital.java
  src/main/java/com/cocos/cocos/db/member/entity/Member.java
  src/main/java/com/cocos/cocos/db/member/entity/MemberAddress.java
  src/main/java/com/cocos/cocos/db/member/entity/MemberHospital.java
  src/main/java/com/cocos/cocos/db/member/repository/MemberHospitalRepository.java
  src/main/java/com/cocos/cocos/enums/message/FailMessage.java
Labels: 🍀feat

#174 Feat: 리뷰 작성 API 구현
  src/main/java/com/cocos/cocos/api/review/controller/ReviewController.java
  src/main/java/com/cocos/cocos/api/review/controller/ReviewControllerSwagger.java
  src/main/java/com/cocos/cocos/api/review/dto/request/ReviewAddRequest.java
  src/main/java/com/cocos/cocos/api/review/dto/response/ReviewAddResponse.java
  src/main/java/com/cocos/cocos/api/review/service/ReviewService.java
  src/main/java/com/cocos/cocos/db/review/db/Review.java
  src/main/java/com/cocos/cocos/db/review/db/ReviewImage.java
  src/main/java/com/cocos/cocos/db/review/db/ReviewSummary.java
  src/main/java/com/cocos/cocos/db/review/db/ReviewSummaryOption.java
  src/main/java/com/cocos/cocos/db/review/db/ReviewSymptom.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewImageRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewSummaryOptionRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewSummaryRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewSymptomRepository.java
  src/test/java/com/cocos/cocos/hospital/HospitalServiceTest.java
  src/test/java/com/cocos/cocos/review/ReviewServiceTest.java
Labels: 🍀feat

#178 Feat: 리뷰 요약 조회 API 구현
  src/main/java/com/cocos/cocos/api/review/controller/ReviewController.java
  src/main/java/com/cocos/cocos/api/review/controller/ReviewControllerSwagger.java
  src/main/java/com/cocos/cocos/api/review/dto/response/ReviewSummaryListResponse.java
  src/main/java/com/cocos/cocos/api/review/dto/response/ReviewSummaryResponse.java
  src/main/java/com/cocos/cocos/api/review/service/ReviewService.java
  src/main/java/com/cocos/cocos/db/review/db/ReviewSummaryOption.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewRepository.java
  src/main/java/com/cocos/cocos/db/review/repository/ReviewSummaryRepository.java
  src/test/java/com/cocos/cocos/review/ReviewServiceTest.java
Labels: 🍀feat

#183 Feat: 후기 작성 약관 동의 API 및 약관 동의 여부 조회 API 구현
  src/main/java/com/cocos/cocos/api/member/controller/MemberController.java
  src/main/java/com/cocos/cocos/api/member/controller/MemberControllerSwagger.java
  src/main/java/com/cocos/cocos/api/member/dto/response/MemberReviewTermsAgreeResponse.java
  src/main/java/com/cocos/cocos/api/member/service/MemberService.java
  src/main/java/com/cocos/cocos/db/member/entity/Member.java
  src/test/java/com/cocos/cocos/member/MemberServiceTest.java
Labels: 🍀feat

#185 Feat: 리뷰 요약 옵션 목록 조회 API 구현
  src/main/java/com/cocos/cocos/api/review/controller/ReviewController.java
  src/main/java/com/cocos/cocos/api/review/controller/ReviewControllerSwagger.java
  src/main/java/com/cocos/cocos/api/review/dto/response/ReviewSummaryOptionListResponse.java
  src/main/java/com/cocos/cocos/api/review/dto/response/ReviewSummaryOptionResponse.java
  src/main/java/com/cocos/cocos/api/review/service/ReviewService.java
  src/test/java/com/cocos/cocos/review/ReviewServiceTest.java
Labels: 🍀feat

#191 Fix: 리뷰 요약 조회 및 추가 API 병원 아이디 제약조건 추가
  src/main/java/com/cocos/cocos/api/review/controller/ReviewController.java
  src/main/java/com/cocos/cocos/api/review/controller/ReviewControllerSwagger.java
Labels: 🔧Fix
